*** Settings ***
Documentation     CI-safe end-to-end validation of balanced Pabot execution.
Library           Collections
Resource          ../../src/robot/resources/keywords.robot
Suite Teardown    Cleanup Parallel Smoke


*** Variables ***
${PARALLEL_SMOKE_DIR}    ${EXECDIR}${/}output${/}parallel-smoke-ci


*** Test Cases ***
Smoke - Pabot Executes Balanced Object Batches
    [Documentation]    Verify Pabot schedules and consolidates isolated standard and Tooling work items.
    ${fake_sf}=    Create Fake Sf Launcher    ${PARALLEL_SMOKE_DIR}${/}unsupported-cli
    VAR    ${SF_CLI}    ${fake_sf}    scope=TEST
    @{data_objects}=    Create List    AggregateResult
    @{tooling_objects}=    Create List    DataStatistics
    ${data}    ${tooling}    ${skipped}    ${durations}=
    ...    Run Object Queries With Pabot
    ...    ${data_objects}
    ...    ${tooling_objects}
    ...    ${PARALLEL_SMOKE_DIR}
    Should Be Empty    ${data}
    Should Be Empty    ${tooling}
    Dictionary Should Contain Item    ${skipped}    AggregateResult    INVALID_TYPE
    Dictionary Should Contain Item    ${skipped}    TOOLING::DataStatistics    INVALID_TYPE
    Dictionary Should Contain Key    ${durations}    AggregateResult
    Dictionary Should Contain Key    ${durations}    TOOLING::DataStatistics

Smoke - Concurrent CLI Results Stay With Their Objects
    ${fake_sf}=    Create Fake Sf Launcher    ${PARALLEL_SMOKE_DIR}${/}fake-cli
    VAR    ${SF_CLI}    ${fake_sf}    scope=TEST
    VAR    ${PABOT_PROCESSES}    ${2}    scope=TEST
    VAR    ${PABOT_SHARDS_PER_PROCESS}    ${2}    scope=TEST
    @{data_objects}=    Create List    Account    Contact
    @{tooling_objects}=    Create List    ApexClass
    ${data}    ${tooling}    ${skipped}    ${durations}=
    ...    Run Object Queries With Pabot
    ...    ${data_objects}
    ...    ${tooling_objects}
    ...    ${PARALLEL_SMOKE_DIR}${/}fake-run
    Dictionary Should Contain Item    ${data}    Account    ${42}
    Dictionary Should Contain Item    ${data}    Contact    ${7}
    Dictionary Should Contain Item    ${tooling}    ApexClass    ${3}
    Should Be Empty    ${skipped}
    Length Should Be    ${durations}    3

Smoke - Tooling Discovery Failure Is Operational
    ${fake_sf}=    Create Fake Sf Launcher    ${PARALLEL_SMOKE_DIR}${/}discovery-cli
    VAR    ${SF_CLI}    ${fake_sf}    scope=TEST
    VAR    ${API_VERSION}    65.0    scope=TEST
    ${objects}    ${reason}=    Get Tooling Object Names
    Should Be Empty    ${objects}
    Should Be Equal    ${reason}    TOOLING_DISCOVERY_FAILED

Smoke - Unexpected Worker Error Preserves Artifact
    VAR    ${SF_CLI}    ${PARALLEL_SMOKE_DIR}${/}missing-sf    scope=TEST
    @{data_objects}=    Create List    Account
    @{tooling_objects}=    Create List
    ${data}    ${tooling}    ${skipped}    ${durations}=
    ...    Run Object Queries With Pabot
    ...    ${data_objects}
    ...    ${tooling_objects}
    ...    ${PARALLEL_SMOKE_DIR}${/}worker-error-run
    Should Be Empty    ${data}
    Should Be Empty    ${tooling}
    Dictionary Should Contain Item    ${skipped}    Account    WORKER_ERROR
    Dictionary Should Contain Key    ${durations}    Account

Smoke - Query Timeout Terminates Process
    ${fake_sf}=    Create Fake Sf Launcher    ${PARALLEL_SMOKE_DIR}${/}timeout-cli
    VAR    ${SF_CLI}    ${fake_sf}    scope=TEST
    VAR    ${MAX_QUERY_TIMEOUT_SECONDS}    ${1}    scope=TEST
    VAR    ${POLL_INTERVAL_SECONDS}    ${0.1}    scope=TEST
    ${count}    ${reason}    ${duration}=    Get Record Count Safe    SleepObject
    Should Be Equal    ${count}    ${None}
    Should Be Equal    ${reason}    TIMEOUT
    Should Be True    ${duration} >= 1


*** Keywords ***
Create Fake Sf Launcher
    [Documentation]    Create a platform-specific executable wrapper around the deterministic fake sf fixture.
    [Arguments]    ${launcher_directory}
    Create Directory    ${launcher_directory}
    ${python}=    Current Python Executable
    ${fake_script}=    Normalize Path    ${CURDIR}${/}..${/}fakes${/}fake_sf.py
    ${is_windows}=    Evaluate    __import__('os').name == 'nt'
    IF    ${is_windows}
        ${launcher}=    Normalize Path    ${launcher_directory}${/}sf.cmd
        ${content}=    Set Variable    @echo off\r\n"${python}" "${fake_script}" %*\r\n
        Create File    ${launcher}    ${content}
    ELSE
        ${launcher}=    Normalize Path    ${launcher_directory}${/}sf
        ${content}=    Set Variable    #!/usr/bin/env sh\nexec "${python}" "${fake_script}" "$@"\n
        Create File    ${launcher}    ${content}
        ${chmod}=    Run Process    chmod    +x    ${launcher}
        Should Be Equal As Integers    ${chmod.rc}    0
    END
    RETURN    ${launcher}

Cleanup Parallel Smoke
    [Documentation]    Remove only the runtime artifacts generated by this smoke suite.
    Run Keyword And Ignore Error    Remove Directory    ${PARALLEL_SMOKE_DIR}    recursive=${TRUE}
